title: Luke Kelly #your name (or website title) here
logo: "/images/profilepic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Father, Husband, Student, Veteran, and Leader.<br>
  This is my page where I will display some of my code and the small projects I have been working on.
  <br><br>
  I have been reading Robert Martin's "Clean Code" quite a bit lately so my code mite have a lot of minor changes.
  <br><br>
  <a href="https://www.linkedin.com/in/lkelly93/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
